### PR TITLE
[comment][xs] - save GitHub keys to environment variables

### PR DESCRIPTION
**Pull request by lauragift21**

### CODE REVIEW

**Comment by roll** [comment]
Hi, where are the keys stored now? After a quick look my guess - as a plain text inside the bundle. Or i miss something

**Comment by lauragift21** [comment]
Yeah I stored them in `.env` file. Following a comment from @Irio about not exposing secret keys. But I guess I could add a comment in the README stating where anyone can find the keys when needed.

**Comment by roll** [comment]
@lauragift21 
I mean a different thing - we still have a serious security breach - https://github.com/frictionlessdata/website-v2/blob/gh-pages/assets/js/app.e8dbf500.js (search for `clientSecret`)

Actually, I'm not sure that with Github deployment it can be resolved

**Comment by lauragift21** [comment]
Oh wow! I see that what would you recommend as a fix?

**Comment by roll** [comment]
@lauragift21 
I would:
- search for ideas of storing secrets on Github Pages
- search for ideas of storing secrets for Vssue
- if nothing consider moving deployment to something like now.sh

In general, I'm not sure how this problem can be solved

**Comment by lauragift21** [comment]
Alright thanks, @roll. I will look into these and hopefully find a better way of handling secrets.

**Comment by roll** [comment]
@lauragift21 
I think it makes sense to disable all the keys for now as it's very dangerous based on the permissions it asks

**Comment by roll** [comment]
It should be a very common problem - the docs of the commenting system have to cover it somehow

**Comment by lauragift21** [comment]
You mean disabling the plugin then. Because it won't work without the keys? @roll

**Comment by roll** [comment]
Disabling plugin but the main thing is removing all the keys otherwise all the registered users are in danger

**Comment by lauragift21** [comment]
Alright will do that.

**Pull request merged**
